---
name: baidunetdisk
run-name: build ${{inputs.version}}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version to build
        default: 4.17.7
        type: string

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: build
        env:
          VERSION: ${{ inputs.version }}
        run: |
          sudo apt update
          sudo apt install libfuse2
          bash baidunetdisk-builder.sh

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}
        run: |
          gh release create "${VERSION}" --notes "Baidu Netdisk ${VERSION}" --title "Baidu Netdisk ${VERSION}" --repo "${{github.repository}}" || true
          gh release upload "${VERSION}" "baidunetdisk-${VERSION}-x86_64.AppImage" --clobber --repo "${{github.repository}}"
          gh release upload "${VERSION}" "baidunetdisk-${VERSION}-x86_64.tar.xz" --clobber --repo "${{github.repository}}"

          gh release create "baidunetdisk" --prerelease --notes "Baidu Netdisk ${VERSION}" --title "Baidu Netdisk ${VERSION}" --repo "${{github.repository}}" || true
          gh release edit "baidunetdisk" --prerelease --notes "Baidu Netdisk ${VERSION}" --title "Baidu Netdisk ${VERSION}" --repo "${{github.repository}}" || true
          mv baidunetdisk-${VERSION}-x86_64.AppImage baidunetdisk-x86_64.AppImage
          mv baidunetdisk-${VERSION}-x86_64.tar.xz baidunetdisk-x86_64.tar.xz
          gh release upload "baidunetdisk" "baidunetdisk-x86_64.AppImage" --clobber --repo "${{github.repository}}"
          gh release upload "baidunetdisk" "baidunetdisk-x86_64.tar.xz" --clobber --repo "${{github.repository}}"
